#cloud-config
package_update: true
packages:
  - git
  - curl

write_files:
  - path: /usr/local/bin/setup_crawler.sh
    owner: root:root
    permissions: '0755'
    content: |
      #!/bin/bash
      set -euo pipefail
      exec > /var/log/setup_crawler.log 2>&1
      echo "[INFO] Installing Docker..."
      curl -fsSL https://get.docker.com/ | sh
      echo "[INFO] Cloning repository..."
      cd /home/ubuntu
      git clone https://github.com/xuananhgit94/crawler-demo.git
      cd crawler-demo
      cd /home/ubuntu/crawler-demo
      echo "[INFO] Creating Docker network..."
      docker network create crawler
      echo "[INFO] Starting docker-compose stack..."
      docker compose -f docker-compose-server.yaml up -d
      echo "[INFO] Waiting for services..."
      curl -sOL https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
      chmod +x wait-for-it.sh
      ./wait-for-it.sh -t 0 localhost:5432 -- echo "Postgres up"
      ./wait-for-it.sh -t 0 localhost:8083 -- echo "Kafka Connect up"
      sleep 180
      echo "[INFO] Running migrations..."
      docker run --env-file=./migrate/.env.container --net crawler xuananhdocker/migrate /app/run init
      docker run --env-file=./migrate/.env.container --net crawler xuananhdocker/migrate /app/run migrate
      echo "[INFO] Creating connectors..."
      echo "CURL (current directory: $(pwd)"
      curl -i -X POST -H "Accept:application/json" -H "Content-Type:application/json" \
        http://localhost:8083/connectors -d @configs/connector/postgres-source.json
      curl -i -X POST -H "Accept:application/json" -H "Content-Type:application/json" \
        http://localhost:8083/connectors -d @configs/connector/elasticsearch-sink.json
      sleep 50
      sudo docker start crawler
      sudo docker start consumer
runcmd:
  - [ bash, -c, "/usr/local/bin/setup_crawler.sh || true" ]